"""Shared Nimbus protocol package."""

from nimbus_protocol.errors import (
    NimbusDisplayError,
    NimbusError,
    NimbusErrorCategory,
    NimbusErrorCode,
    error_from_exception,
)
from nimbus_protocol.models import (
    ActionSummary,
    ApprovalChoice,
    ApprovalDecision,
    ApprovalRequest,
    ArtifactSummary,
    ChatTurnInput,
    ChatTurnResult,
    ConfirmationDetails,
    NimbusEvent,
    PermissionEffect,
    PermissionRule,
    SessionRef,
    StreamEventType,
    TurnAttachment,
    TurnOutcome,
    TurnResumeCommand,
    TurnStartCommand,
    event_from_mapping,
)

__all__ = [
    "ActionSummary",
    "ApprovalChoice",
    "ApprovalDecision",
    "ApprovalRequest",
    "ArtifactSummary",
    "ChatTurnInput",
    "ChatTurnResult",
    "ConfirmationDetails",
    "NimbusDisplayError",
    "NimbusError",
    "NimbusErrorCategory",
    "NimbusErrorCode",
    "NimbusEvent",
    "PermissionEffect",
    "PermissionRule",
    "SessionRef",
    "StreamEventType",
    "TurnAttachment",
    "TurnOutcome",
    "TurnResumeCommand",
    "TurnStartCommand",
    "error_from_exception",
    "event_from_mapping",
]
